version: '3.5'

services:
  db:
    container_name: postgres_db
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
      - POSTGRES_DB=notes-db
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    expose:
      - 5432

  backend:
    container_name: backend
    build:
      context: backend
    networks:
      - db
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/notes-db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    expose:
      - 8080
  
  frontend:
    container_name: frontend
    build:
      context: frontend
      args:
        - VITE_APP_BACKEND_HOST=http://${HOSTNAME}:8080
    ports:
      - 5173:5173
    networks:
      - db
    depends_on:
      - backend
    expose:
      - 5173

networks:
  db:
    driver: bridge
volumes:
  db: {}